### ISSUE TITLE
Can't login to epic games

### ISSUE THREAD

**Issue by LOCKhart07** [vogler/free-games-claimer#260]
Error
![image](https://github.com/vogler/free-games-claimer/assets/33950242/32fbce40-2e51-4b88-bd45-ed55d4ebeb6d)

I checked and I have commit - a374d48 that was mentioned in a previous issue

**Comment by WalkingSteph** [comment]
In the current version the commit is already merged but the timeout in the screenshot from [LOCKhart07] still exists.
But only if i use it outside docker... inside docker if have the captcha issue

**Comment by TheButterbrotMan** [comment]
Yep, yesterday it worked. But today getting this error.

**Comment by GodzillaTV** [comment]
will this error be fixed?

**Comment by vogler** [comment]
I'll probably have some time around the holidays if it's not a fast fix.
First have to check which of all these issues are duplicates... Should add issue templates.

Did you try to login in the browser (`SHOW=1`)?

**Comment by GodzillaTV** [comment]
I can't. VNC and noVNC both do not work.

**Comment by vogler** [comment]
What do you mean? Are you on HAOS? Shouldn't mix issues.
I'm talking about timeout in the original post.
Run `SHOW=1 node epic-games` on your host, not docker.
Then log in in the browser, not using the CLI. If that works, the password locator changed. Can't test it myself right now.

**Comment by GodzillaTV** [comment]
yes i have the error. but i don´t have access to the browser because i´m on HAOS. And VNC and noVNC didn´t work.

**Comment by vogler** [comment]
And you don't have another machine where you could run it?
https://github.com/vogler/free-games-claimer/wiki/Host-and-run-free-games-claimer-in-the-cloud-periodically

But yea, bad combo 😄 Maybe the HAOS (#149) and captcha (#183) issues will be resolved together by upgrading the OS and changing to TigerVNC.

**Comment by GodzillaTV** [comment]
Yes, thats the problem at the moment

**Comment by vogler** [comment]
They changed some things:
- the captcha now already comes before entering the password - that's why you got the timeout waiting for `#password`.
- locators for the captcha iframe and 'Incorrect response' changed

The captcha challenge detection should be fixed, but I'm now also getting an 'unsolvable' captcha during login.

**Comment by vogler** [comment]
Ok, with `SHOW=1` instead of `PWDEBUG=1` I didn't get any captcha on macOS:
```console
❯ SHOW=1 DRYRUN=1 BROWSER_DIR=data/browser3 node epic-games.js
2023-12-21 02:01:07.716 started checking epic-games
startup: 2.927s
Not signed in anymore. Please login in the browser or here in the terminal.
Login timeout is 180 seconds!
Press ESC to skip the prompts if you want to login in the browser (not possible in headless mode).
✔ Enter password · ********
Enter the security code to continue - This appears to be a new device, browser or location. A security code has been sent to your email address at ...
Signed in as ...
login: 20.147s
Free games: [ 'https://store.epicgames.com/en-US/p/dnf-duel-07d055' ]
Current free game: DNF Duel
  Not in library yet! Click GET.
  DRYRUN=1 -> Skip order!
claim game: 5.028s
claim all games: 5.226s
Recorded video: /Users/voglerr/dev/Web/free-games-claimer/data/record/8214ccc0-9c64-4262-9f1e-f00779618f7d.webm
```

So, this issue is solved. Captcha for docker is tracked in #183.

**Comment by TheButterbrotMan** [comment]
Im running this script on a headless debian instance, and still getting the captcha error.
`Not signed in anymore. Please login in the browser or here in the terminal.
Login timeout is 180 seconds!
Using email and password from environment.
Got a captcha during login (likely due to too many attempts)! You may solve it in the browser, get a new IP or try again in a few hours.`

**Comment by Shirotaku** [comment]
If anyone is struggeling with unsolvable captchas:
Try linking your epic account with steam and login this way. This worked for me!

**Comment by julianrios** [comment]
@Shirotaku thanks! I was able to login but the captchas are now on each game thinking its some issue with how epic is setup

**Comment by timothe** [comment]
> If anyone is struggeling with unsolvable captchas: Try linking your epic account with steam and login this way. This worked for me!

How can you ask FGC to do that?
