### ISSUE TITLE
[EPIC STORE] age confirmation with age dropdown

### ISSUE THREAD

**Issue by Blazzycrafter** [vogler/free-games-claimer#275]
if the store wants an birthday then this does NOT enable the "confirmation"....

i must use the Show env to set the birthday

![image](https://github.com/vogler/free-games-claimer/assets/39300111/3e695282-2694-4d85-b994-191b56635dca)

but after the set per dropdown the confim butten got detected as enabled and continued as normal

**Comment by vogler** [comment]
I don't remember seeing this. Is this a one time prompt or does it appear every time?
I've also already claimed Fallout 3, so can't really inspect it.
Can you add some screenshots of the DOM (right click > Inspect)?

**Comment by vogler** [comment]
Ok, no, I get it too if I open the page in incognito mode:
<img width="1792" alt="image" src="https://github.com/vogler/free-games-claimer/assets/493741/bbcd26c1-e94a-4f77-988a-4c96e6ad8a2b">
Sadly no input element but some custom element.
Maybe we can set some cookie to not show it. If I'm logged in in Chrome, I don't get it.

**Comment by voruti** [comment]
I got it yesterday within the Epic Games Launcher (where I'm logged in).

And just now as well...

**Comment by yoshimo** [comment]
HasAcceptedAgeGates seems a likely cookie

```
HasAcceptedAgeGates
EPIC SUGGESTED RATING:18,USK:9007199254740991```

**Comment by vogler** [comment]
Should be fixed. Luckily the USK value doesn't seem to matter.

**Comment by damiantrx** [comment]
Unlucky, looks like it still exists after previously running with a date of birth setting.

```sh
Free games: [
  'https://store.epicgames.com/en-US/p/the-outer-worlds-spacers-choice-edition'
]
  This game contains mature content recommended only for ages 18+
  Got "To continue, please provide your date of birth" - This shouldn't happen due to cookie set above. Please report to https://github.com/vogler/free-games-claimer/issues/275
--- Exception:
page.click: Timeout 60000ms exceeded.
Call log:
  - waiting for locator('button:has-text("Continue")')
  -   locator resolved to <button disabled class="css-1c0mm3y" aria-disabled="true…>…</button>
  - attempting click action
  -   waiting for element to be visible, enabled and stable
  -     element is not enabled - waiting...

    at /fgc/epic-games.js:155:18
```

**Comment by yobson1** [comment]
Also still having this issue 

```
Free games: [
  'https://store.epicgames.com/en-US/p/the-outer-worlds-spacers-choice-edition'
]
  This game contains mature content recommended only for ages 18+
  Got "To continue, please provide your date of birth" - This shouldn't happen due to cookie set above. Please report to https://github.com/vogler/free-games-claimer/issues/275
Current free game: The Outer Worlds: Spacer's Choice Edition
  Not in library yet! Click GET.
  Claimed successfully!
```

Continued successfully after I manually input a DoB

**Comment by vogler** [comment]
Ok, strange, setting the cookie worked fine for 'Fallout 3' for me and 'The Outer Worlds' is USK 16 for me, so no problem.
For Fallout, it did show the age confirmation box, but then immediately closed it again. However, logic-wise it shouldn't be a timing issue.
Can you please post the value of your `HasAcceptedAgeGates` cookie? Mine is still the one from Fallout:
<img width="1177" alt="image" src="https://github.com/vogler/free-games-claimer/assets/493741/13929cd4-b0c9-417b-8d02-8a3341d65fd5">

For 'The Outer Worlds' I'm not even getting the mature content message, so the age rating probably depends on the region of your account (mine is DE).

```console
$ node epic-games.js
2023-12-26 16:20:54.555 started checking epic-games
startup: 3.360s
Signed in as ...
login: 3.635s
Free games: [
  'https://store.epicgames.com/en-US/p/the-outer-worlds-spacers-choice-edition'
]
Current free game: The Outer Worlds: Spacer's Choice Edition
  Not in library yet! Click GET.
  Claimed successfully!
claim game: 13.278s
claim all games: 13.842s
```

**Comment by yobson1** [comment]
![image](https://github.com/vogler/free-games-claimer/assets/45133474/549a6f14-2d8f-4fce-a89e-2da0e2e19ed4)

Is what it's set as while claiming today's game, Human Resource Machine

**Comment by yobson1** [comment]
Having the same issue again today with the Saints Row game being claimed

**Comment by yoshimo** [comment]
egs_age_gate_dob contains the date of birth
EGS_VAULT_UNLOCK is also a cookie that might play into it.

**Comment by vogler** [comment]
Strange, for me, for Saints Row, the cookie that's already set is enough.

**Comment by vogler** [comment]
It will now enter a date of birth if the age confirmation pops up.
Maybe we can still figure out which cookies prevent this afterwards.

**Comment by yobson1** [comment]
I think it's region specific like you suggested before. I believe USK is the ratings board in Germany, right? PEGI is the ratings board in most of Europe. I'm in the UK and when I entered a DoB `HasAcceptedAgeGates` had `PEGI: 18` instead of a USK value.
