### ISSUE TITLE
GOG AND EG Don't work

### ISSUE THREAD

**Issue by ccsimplyspolit** [vogler/free-games-claimer#334]
GOG :
![изображение](https://github.com/vogler/free-games-claimer/assets/29892758/4c17e558-082a-4823-8f16-021349218547)
![изображение](https://github.com/vogler/free-games-claimer/assets/29892758/69181301-aa82-4084-8765-7e73e7051f19)
![изображение](https://github.com/vogler/free-games-claimer/assets/29892758/74af9671-0641-4b3e-aca5-0df68a11deab)
EG:
![изображение](https://github.com/vogler/free-games-claimer/assets/29892758/7d1ae0f9-0374-45ee-9b9e-6a4d51a6856c)
![изображение](https://github.com/vogler/free-games-claimer/assets/29892758/40876451-9857-496c-8f23-fd7d4a0e8679)
![изображение](https://github.com/vogler/free-games-claimer/assets/29892758/efaeac13-a816-4613-85cc-35f101cf3ee5)
![изображение](https://github.com/vogler/free-games-claimer/assets/29892758/630ccc78-87ef-48cd-975c-2ce79574ec05)

**Comment by vogler** [comment]
GOG is fixed, for EG captcha there are already several issues.

**Comment by ccsimplyspolit** [comment]
looks like still not fixed, (when nothing to claim)
main
2024-06-23 19:51:43.359 started checking gog
--- Exception:
[AggregateError: All promises were rejected] {
  [errors]: [
    locator.waitFor: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('a:has-text("Sign in")').first() to be visible
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>
      -   locator resolved to hidden <a hook-test="menuAnonymousButton" ng-click="anonym…>…</a>

        at D:\claim_games\FGC\free-games-claimer\gog.js:41:29,
    page.waitForSelector: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('#menuUsername') to be visible
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" class="men…></span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" class="men…></span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>
      -   locator resolved to hidden <span id="menuUsername" data-hj-suppress="" ng-bind="a…>sshunko</span>

        at D:\claim_games\FGC\free-games-claimer\gog.js:41:45
  ]
}

**Comment by vogler** [comment]
If you spam duplicates, it's not helpful.
